// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoviesLibraryApp.Models;

public partial class Medium
{
    public int Id { get; set; }

    public string Media { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}