// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoviesLibraryApp.Models;

public partial class Movie
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateTime? PublishDate { get; set; }

    public int? CategoryId { get; set; }

    public int? MediaId { get; set; }

    public double? Rating { get; set; }

    public string? Picture { get; set; }

    public string Watched { get; set; }

    public DateTime? WatchedDate { get; set; }

    public virtual Category Category { get; set; }

    public virtual Medium Media { get; set; }

    public virtual ICollection<MovieActor> MovieActors { get; set; } = new List<MovieActor>();

}